# Generated by Django 4.1.2 on 2023-03-15 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('no_control', models.CharField(max_length=8, verbose_name='No. Control')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumnos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entrega_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección del archivo')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.alumnos', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Entrega de documento',
                'verbose_name_plural': 'Entregas de documentos',
                'db_table': 'entrega_documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=5, verbose_name='Extensión')),
            ],
            options={
                'verbose_name': 'Tipo de archivo',
                'verbose_name_plural': 'Tipos de archivos',
                'db_table': 'tipo_archivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('tamano_MB', models.IntegerField(default=4, verbose_name='Tamaño en MB')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
                'db_table': 'tipo_documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('tiempo_estimado', models.IntegerField(default=5, verbose_name='Días estimados')),
                ('habilitado', models.BooleanField(verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Tipo de tramite',
                'verbose_name_plural': 'Tipos de tramites',
                'db_table': 'tipo_tramites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.alumnos', verbose_name='Alumno')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_tramites', verbose_name='Tramite')),
            ],
            options={
                'verbose_name': 'Tramite',
                'verbose_name_plural': 'Tramites',
                'db_table': 'tramites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rel_Tram_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.rol', verbose_name='Rol')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_tramites', verbose_name='Tramite')),
            ],
            options={
                'db_table': 'rel_tram_rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rel_Tram_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_documentos', verbose_name='Documento')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_tramites', verbose_name='Tramite')),
            ],
            options={
                'db_table': 'rel_tram_doc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rel_Empl_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.empleados', verbose_name='Empleado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.rol', verbose_name='Rol')),
            ],
            options={
                'db_table': 'rel_emp_rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rel_Doc_TipoArch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_documentos', verbose_name='Documento')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_archivos', verbose_name='Extensión')),
            ],
            options={
                'db_table': 'rel_doc_tiparch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Observ_Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=100, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.estados', verbose_name='Estado')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.empleados', verbose_name='Supervisor')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tramite', verbose_name='Tramite')),
            ],
            options={
                'verbose_name': 'Observación del tramite',
                'verbose_name_plural': 'Observaciones del tramite',
                'db_table': 'observ_tramites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Observ_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=100, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.entrega_doc', verbose_name='Documento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.estados', verbose_name='Estado')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.empleados', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Observación del documento',
                'verbose_name_plural': 'Observaciones del documento',
                'db_table': 'observ_doc',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='entrega_doc',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_documentos', verbose_name='Tipo de documento'),
        ),
    ]
