# Generated by Django 4.1.2 on 2023-03-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'managed': True, 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='entrega_doc',
            options={'managed': True, 'verbose_name': 'Entrega de documento', 'verbose_name_plural': 'Entregas de documentos'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': True, 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='observ_doc',
            options={'managed': True, 'verbose_name': 'Observación del documento', 'verbose_name_plural': 'Observaciones del documento'},
        ),
        migrations.AlterModelOptions(
            name='observ_tramite',
            options={'managed': True, 'verbose_name': 'Observación del tramite', 'verbose_name_plural': 'Observaciones del tramite'},
        ),
        migrations.AlterModelOptions(
            name='tipo_archivo',
            options={'managed': True, 'verbose_name': 'Tipo de archivo', 'verbose_name_plural': 'Tipos de archivos'},
        ),
        migrations.AlterModelOptions(
            name='tipo_documento',
            options={'managed': True, 'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documentos'},
        ),
        migrations.AlterModelOptions(
            name='tipo_tramite',
            options={'managed': True, 'verbose_name': 'Tipo de tramite', 'verbose_name_plural': 'Tipos de tramites'},
        ),
        migrations.AlterModelOptions(
            name='tramite',
            options={'managed': True, 'verbose_name': 'Tramite', 'verbose_name_plural': 'Tramites'},
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='descr',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='entrega_doc',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.alumnos', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='entrega_doc',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección del archivo'),
        ),
        migrations.AlterField(
            model_name='entrega_doc',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_documento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='observ_doc',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.comentarios', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='observ_doc',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.entrega_doc', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='observ_doc',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='observ_doc',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='observ_doc',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.empleados', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='observ_tramite',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.comentarios', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='observ_tramite',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='observ_tramite',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='observ_tramite',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.empleados', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='observ_tramite',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tramite', verbose_name='Tramite'),
        ),
        migrations.AlterField(
            model_name='rel_tram_doc',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_documento', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='rel_tram_doc',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_tramite', verbose_name='Tramite'),
        ),
        migrations.AlterField(
            model_name='rel_tram_rol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.rol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='rel_tram_rol',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_tramite', verbose_name='Tramite'),
        ),
        migrations.AlterField(
            model_name='tipo_archivo',
            name='extension',
            field=models.CharField(max_length=5, verbose_name='Extensión'),
        ),
        migrations.AlterField(
            model_name='tipo_documento',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipo_documento',
            name='tamano_MB',
            field=models.IntegerField(default=4, verbose_name='Tamaño en MB'),
        ),
        migrations.AlterField(
            model_name='tipo_documento',
            name='tipo_arch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_archivo', verbose_name='Tipo de archivo'),
        ),
        migrations.AlterField(
            model_name='tipo_tramite',
            name='habilitado',
            field=models.BooleanField(verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='tipo_tramite',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipo_tramite',
            name='tiempo_estimado',
            field=models.IntegerField(default=5, verbose_name='Días estimados'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.alumnos', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tipo_tramite', verbose_name='Tramite'),
        ),
    ]
